///////////////////////////////////////////////////////////////////////////
/// COMPILE_MAIN=ZIPsFS                                                 ///
/// In memory cache                                                     ///
/// Caching file data in main memory                                    ///
/// Usually applies to compressed ZIP entries and                       ///
/// autogenerated content and special files                             ///
///////////////////////////////////////////////////////////////////////////

// Todo fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
_Static_assert(WITH_PRELOADRAM,"");
#include "cg_crc32.c"
#define is_preloadram(d,r) _viamacro_is_preloadram(d,r,__func__,__LINE__)

#define PRS(d) (d->preloadram->preloadram_status)
#define ASSERT_D_READING(d) ASSERT(is_preloadram(d,NULL)); if(PRS(d)!=PRELOADRAM_READING) DIE_DEBUG_NOW("%s status=%d %s",D_VP(d),PRS(d),enum_preloadram_status_S[PRS(d)]);
////////////////////////////////////
/// Parameters from command line ///
////////////////////////////////////
static bool preloadram_set_maxbytes(const char *s){
  if ((_preloadram_bytes_limit=cg_atol_kmgt(s))<(1<<22)){
    log_error("Option -l: _preloadram_bytes_limit is too small %s\n",s);
    return false;
  }
  return true;
}
static bool preloadram_set_policy(const char *a){
  bool ok=false;
  const char *s;
  for(int i=0;!ok && (s=rm_pfx_us(enum_when_preloadram_zip_S[i]));i++){
    if ((ok=!strcasecmp(s,a))) _preloadram_policy=i;
  }
  if (!ok){ log_error("Wrong option -c %s\n",a); ZIPsFS_usage(); }
  if (WITH_DEBUG_ALL_ZIP_PRELOADRAM && ! cg_uid_is_developer()){ _preloadram_policy=PRELOADRAM_ALWAYS; }
  return ok;
}
///////////////////////////////
/// Decide for cache in RAM ///
///////////////////////////////
#define ramUsageForFilecontent()  (atomic_load(_countersB1+COUNT_TXTBUF_SEGMENT_MMAP)-atomic_load(_countersB2+COUNT_TXTBUF_SEGMENT_MMAP)+atomic_load(_countersB1+COUNT_TXTBUF_SEGMENT_MALLOC)-atomic_load(_countersB2+COUNT_TXTBUF_SEGMENT_MALLOC))

/* File info for virtual-path plus root-path Needed  when loading analysis.tdf, also wait for sufficient RAM  for analysis.tdf_bin */
static bool statForVirtualpathAndRootpath(struct stat *st, const char *vp, const char *rootpath){
  root_t *r=NULL;
  foreach_root(r2) if (r2->rootpath==rootpath) r=r2;
  if (!r) return false;
  NEW_VIRTUALPATH(vp);
  NEW_ZIPPATH(&vipa);
  //log_entered_function("%s r: %p",vp,r);
  const bool ok=find_realpath_for_root(0,zpath,r);
  *st=ok?zpath->stat_vp: empty_stat;
  //log_exited_function("%s found: %d  size: %ld ",vp,ok,st->st_size);
  return ok;
}

/*************************************/
/* Decide whether preloaded into RAM */
/*************************************/
#define B zpath->preloadram_need_bytes
static bool preloadram_advise(zpath_t *zpath, const int additional_flags){
  cg_thread_assert_not_locked(mutex_fhandle);
  if (zpath->dir==DIR_NEVER_PREFETCH_RAM || !zpath->root || _preloadram_policy==PRELOADRAM_NEVER)  return false;
  if (zpath->dir==DIR_PREFETCH_RAM || ZPF(ZP_IS_ZIP)  && _preloadram_policy==PRELOADRAM_ALWAYS){  B=zpath->stat_vp.st_size; return true;  }
  B=config_advise_preload_file_ram(additional_flags|
                                   (ZPF(ZP_IS_COMPRESSEDZIPENTRY)?ADVISE_CACHE_IS_COMPRESSEDZIPENTRY:0)|
                                   (ZPF(ZP_IS_ZIP)?ADVISE_CACHE_IS_ZIPENTRY:0)|
                                   ((_preloadram_policy==PRELOADRAM_COMPRESSED&&ZPF(ZP_IS_COMPRESSEDZIPENTRY) || ZPF(ZP_IS_ZIP)&&_preloadram_policy==PRELOADRAM_ALWAYS)?ADVISE_CACHE_BY_POLICY:0),
                                   VP(),VP_L(),rootpath(zpath->root),zpath->stat_vp.st_size);
  if (B<=0) return false;
  if (B>_preloadram_bytes_limit){
    warning(WARN_PRELOADRAM|WARN_FLAG_ONCE,VP(),"%'lld>%'lld. Consider set byte limit for RAM cache with  "ANSI_FG_BLUE"-l <gigabytes>G"ANSI_RESET,LLD(B),LLD(_preloadram_bytes_limit));
    return false;
  }
  return true;
}

/* Each pass less strict */
static bool preloadram_is_free_ram(const char *func,fHandle_t *d, const float laxity){
  LOCK_N(mutex_fhandle, const bool ok=d->preloadram && d->preloadram->txtbuf);
  if (ok) return true;
  off_t size=d->zpath.preloadram_need_bytes;
  if (size<=0) size=D_ST_SIZE(d);
  if (_preloadram_bytes_limit*laxity>ramUsageForFilecontent()+size) return true;
  log_verbose("%s High RAM usage:  %s usage:%'lld  filesize:%'lld  limit:%'lld   laxity:%2.3f\n",func, D_VP(d),LLD(ramUsageForFilecontent()), LLD(size),LLD(_preloadram_bytes_limit),laxity);
  return false;
}


/* Invoked from xmp_read, where fHandle_t *d=fhandle_get(path,fd) */
static off_t preloadram_wait_and_read(char *buf, const off_t size, const off_t offset,fHandle_t *d){
  //log_entered_function("%s ",D_VP(d));
  const zpath_t *zpath=&d->zpath;
  ASSERT(d->flags&WITH_PRELOADRAM);
  for(int i=100; !preloadram_is_free_ram(__func__,d,i/99.99);i++) usleep(1<<20);

  if (!preloadram_wait(d,offset+size)){ warning(WARN_PRELOADRAM|WARN_FLAG_FAIL,VP()," %p preloadram_wait returned false",d);return -1;}
  LOCK_N(mutex_fhandle,const off_t preloadram_l=is_preloadram(d,NULL)? d->preloadram->preloadram_l: -1); /* Otherwise md5sum fails with EPERM */
  /* This rtelation is not generally true: (preloadram_l>=size+offset); */
  if (preloadram_l<0){ warning(WARN_PRELOADRAM|WARN_FLAG_FAIL,VP(),"preloadram_l:%ld",preloadram_l);return -1;}
  if (offset==preloadram_l) return 0;
  if (preloadram_l){
    LOCK_N(mutex_fhandle,const off_t num=preloadram_read(buf,d,offset,size+offset));
    if (num>0) COUNTER1_INC(COUNT_READZIP_PRELOADRAM);
    if (num>0 || preloadram_l>=offset) return num; /* Wann passiert das? */
  }
  warning(WARN_PRELOADRAM|WARN_FLAG_FAIL,VP(),"return -1");
  return -1;
}





//////////////
/// Status ///
//////////////
static enum enum_preloadram_status preloadram_get_status(const fHandle_t *d){
  ASSERT_LOCKED_FHANDLE();
  return d && d->preloadram?PRS(d):PRELOADRAM_STATUS_NIL;
}
static void preloadram_set_status(fHandle_t *d,enum enum_preloadram_status status){
  ASSERT_LOCKED_FHANDLE();
  if (!d) return;
  ASSERT(d->preloadram);
  //log_debug_now("%s %p status:%s -> %s",D_VP(d),d,enum_preloadram_status_S[PRS(d)],enum_preloadram_status_S[status]);
  if (status==PRELOADRAM_READING || status==PRELOADRAM_QUEUED)   ASSERT(d->flags&FHANDLE_PRELOADRAM_MASTER);
  if (d->preloadram) PRS(d)=status;
}
//////////////////////////////////
/// Constructor and Destructor ///
//////////////////////////////////



static struct preloadram *preloadram_new(fHandle_t *d){
  ASSERT_LOCKED_FHANDLE();
  if (!d->preloadram){
    d->flags|=FHANDLE_PRELOADRAM_MASTER;
    log_entered_function(ANSI_FG_GREEN"'%s' d: %p "ANSI_YELLOW"%llu"ANSI_RESET" thread: %llx"ANSI_RESET, D_VP(d),d,LLU(d->fhandle_fh),LLU(pthread_self()));
    static int id;
    (d->preloadram=cg_calloc(COUNT_PRELOADRAM_MALLOC,1,sizeof(struct preloadram)))->id=++id;
    d->preloadram->preloadram_l=D_ST_SIZE(d);
    d->preloadram->m_zpath=d->zpath;
    //FOREACH_FHANDLE(ie,e){ if (fhandle_virtualpath_equals(d,e)) e->preloadram=d->preloadram; }
  }
  return d->preloadram;
}
static bool preloadram_try_destroy(fHandle_t *d){
  struct preloadram *m=d->preloadram;
  if (m->preloadram_status==PRELOADRAM_QUEUED ||
      m->preloadram_status==PRELOADRAM_READING || /* Avoid that d gets destroyed and reinitialized while a reference is in the queue or filled with data */
      is_preloadram_shared_with_other(d)) return false;
  log_entered_function(ANSI_FG_RED"'%s' d: %p "ANSI_YELLOW"%llu"ANSI_RESET" thread: %llx"ANSI_RESET, D_VP(d),d,LLU(d->fhandle_fh),LLU(pthread_self()));
  textbuffer_destroy(m->txtbuf);
  FREE_NULL_MALLOC_ID(m->txtbuf);
  cg_free_null(COUNT_PRELOADRAM_MALLOC,d->preloadram);
  foreach_fhandle_also_emty(id,e) if (e->preloadram==m) e->preloadram=NULL;
  return true;
}

/***************************************************************************************************************************/
/* Instances of struct preloadram are shared by instances of fHandle_t,  when a file is open multiple times in the client. */
/***************************************************************************************************************************/
static void preloadram_infer_from_other_handle(fHandle_t *d){
  ASSERT_LOCKED_FHANDLE();
  foreach_fhandle_including_pending_destruct(ie,e){
    if (e->preloadram && fhandle_virtualpath_equals(d,e)){
      if (e->preloadram->preloadram_already==D_ST_SIZE(e) || !(e->flags&FHANDLE_DESTROY_LATER)){ /* Either fully read or still reading */
        d->preloadram=e->preloadram;
        //log_debug_now(GREEN_SUCCESS"%s",D_VP(d));
        break;
      }
    }
  }
  //log_debug_now(RED_FAIL"%s",D_VP(d));
}
static bool is_preloadram_shared_with_other(const fHandle_t *d){
  ASSERT_LOCKED_FHANDLE();
  if (d->preloadram){
    FOREACH_FHANDLE(id,e){
      if (e!=d && e->preloadram==d->preloadram){
        assert(fhandle_virtualpath_equals(d,e));
        return true;
      }
    }
  }
  return false;
}
////////////////////////////////////////////////////////////////////////
///  root_t may change by find_realpath_other_root()               ///
///  Check that preloadram is not NULL and that  root is still correct ///
////////////////////////////////////////////////////////////////////////
static bool _viamacro_is_preloadram(const fHandle_t *d, const root_t *r,const char *func,const int line){
  ASSERT_LOCKED_FHANDLE();
  if (!d) return false;
  if (!d->preloadram){log_verbose("%s:%d !%p->preloadram %s",func,line,d,D_VP(d));return false;}
  if (!d->preloadram->txtbuf){log_verbose("%s:%d !%p->preloadram->txtbuf %s",func,line,d,D_VP(d));return false;}
  if (r && d->preloadram->m_zpath.root!=r){log_verbose("%s:%d wrong root %s",func,line,D_VP(d));return false;}
  return true;
}
/*************************************************************************************************************/
/* No need to continue filling the buffer when  d and  d->preloadram are not used by open file connections.  */
/*************************************************************************************************************/
static bool preloadram_can_stop_reading(const fHandle_t *d){
  ASSERT_LOCKED_FHANDLE();
  if ((d->flags&FHANDLE_DESTROY_LATER) && !fhandle_active_readers_writers(d) && !is_preloadram_shared_with_other(d)){
    if (DEBUG_NOW!=DEBUG_NOW){
      log_debug_now(ANSI_RED"BBBBBBBBBBBBBBBBBBBBB %s"ANSI_RESET,D_VP(d));
      //d->flags|=FHANDLE_DEBUG_WOULD_BREAK;
      return false;
    }
    return true;
  }
  return false;

}

/**********************************************************/
/* Returning the bytes from the buffer RAM                */
/* Called from preloadram_wait_and_read()  and xmp_read() */
/**********************************************************/
static off_t preloadram_read(char *buf,const fHandle_t *d,const off_t from,off_t to){
  ASSERT_LOCKED_FHANDLE();
  if (!d || !d->preloadram || !d->preloadram->txtbuf) return -1;
  to=MIN(to,d->preloadram->preloadram_already);
  if (to==from) return 0; /* Note that returning -1 causes operation not permitted. */
  if (to>from){
    textbuffer_copy_to(d->preloadram->txtbuf,from,to,buf);
    return to-from;
  }
  return d->preloadram->preloadram_already<=from && PRS(d)==PRELOADRAM_DONE?-1:0;
}


/**********************************************************************************/
/* After complete loading into the buffer, compare with crc32 stored in ZIP file  */
/**********************************************************************************/
static bool fhandle_check_crc32(fHandle_t *d){
  ASSERT_LOCKED_FHANDLE();
  if (!is_preloadram(d,NULL) || !d->preloadram->txtbuf->n){
    return false;
  }
  const off_t st_size=D_ST_SIZE(d);
  const uint32_t crc=cg_crc32(textbuffer_first_segment(d->preloadram->txtbuf),st_size,0,_mutex+mutex_crc);
  if (d->zpath.zipcrc32!=crc){
    warning(WARN_PRELOADRAM|WARN_FLAG_ERROR,D_VP(d),"crc32-mismatch!  ZIP: %x != computed: %x size=%zu already: %zu  rp=%s",d->zpath.zipcrc32,crc,st_size,d->preloadram->preloadram_already,D_RP(d));
    return false;
  }
  //log_verbose(GREEN_SUCCESS"crc32  %x  size=%zu already: %zu  rp=%s",crc,st_size,d->preloadram->preloadram_already,D_VP(d));
  return true;
}


/********************************************************************************************************************/
/* Reading the file / zipentry into buffer.                                                                         */
/* This is called from an infinity loop which processes all fHandle_t with PRELOADRAM_QUEUED */
/* While in here or in preloadram_wait(), the preloadram_status is PRELOADRAM_QUEUED or PRELOADRAM_READING. */
/* fHandle_t with this preloadram_status are  guaranteed not to be destroyed.                                          */
/* Reading should complete unless preloadram_can_stop_reading(d).                                                     */
/* Since root and realpath may change in preloadram->m_zpath, we make a copy of the real path                       */
/********************************************************************************************************************/

static void preloadram_now(fHandle_t *d, root_t *r){
  ASSERT(d->flags&FHANDLE_PRELOADRAM_MASTER);
  //static int count;log_entered_function("%s  #%d",VP(),++count);
  char rp[PATH_MAX];
  LOCK_N(mutex_fhandle, strcpy(rp,ZP_RP(&d->preloadram->m_zpath)); const off_t st_size=D_ST_SIZE(d); const bool iszip=(d->zpath.flags&ZP_IS_ZIP));
  log_entered_function("%s  textbuffer_memusage  ram-usage: %'lld d: %p "ANSI_YELLOW"%llu"ANSI_RESET" thread: %llx",D_VP(d),LLD(ramUsageForFilecontent()),d,LLU(d->fhandle_fh),LLU(pthread_self()));
  cg_thread_assert_not_locked(mutex_fhandle);
  const int64_t start=currentTimeMillis();
  const int fd=iszip?0:open(rp,O_RDONLY); // USED_TO_BE_ZP_TRY_ZIP
  zip_file_t *zf=NULL;
  zip_t *za=NULL;
  if (iszip){
    zf=my_zip_fopen( (za=my_zip_open(rp)),D_EP(d),ZIP_RDONLY,rp);
    if (!zf){ my_zip_fclose(zf,rp); return;}
  }
  if (!zf && fd<=0){ warning(WARN_PRELOADRAM|WARN_FLAG_ERRNO|WARN_FLAG_ERROR,rp,"Failed %s() d: %p",iszip?"zip_open":"open",d);  return;}
  off_t already=0;
      lock(mutex_fhandle);
      ASSERT_D_READING(d);
      PRELOADFILE_ROOT_UPDATE_TIME(d,r,true);
  unlock(mutex_fhandle);
  bool more=false, ok=true;
  char *dst=textbuffer_first_segment_with_min_capacity(st_size>THRESHOLD_MALLOC_MMAP?TXTBUFSGMT_MUNMAP:0,d->preloadram->txtbuf,st_size);
  if (!dst){ warning(WARN_PRELOADRAM,rp,"dst is NULL"); DIE_DEBUG_NOW("");   return;}
  for(;st_size>already;){
    const off_t n_max=MIN_long(PRELOADRAM_READ_BYTES_NUM,st_size-already), n=zf?my_zip_fread(zf,dst+already,n_max,rp):read(fd,dst+already,n_max);
    if (!n) break;
    if (n<0){ok=false;warning(WARN_PRELOADRAM,rp,"n<0  d: %p  read=%'zu st_size=%'ld",d,already,st_size);break;}
        lock(mutex_fhandle); /* copy bytes */

        ASSERT_D_READING(d);
        more=!preloadram_can_stop_reading(d);
        //if (!ok)log_debug_now(RED_FAIL"ok=%d  is_preloadram:%d  preloadram_can_stop_reading:%d already=%'ld  thread: %lx", ok,is_preloadram(d,r), preloadram_can_stop_readingc(d),  already, pthread_self());
        if (d->preloadram && d->preloadram->txtbuf){
          //char *dst=textbuffer_first_segment_with_min_capacity(st_size>THRESHOLD_MALLOC_MMAP?TXTBUFSGMT_MUNMAP:0,d->preloadram->txtbuf,st_size);
          if (dst!=NULL){
            //log_debug_now("already: %'ld n:%'ld  Plus: %'ld  st_size: %'ld d: %p "ANSI_YELLOW"%llu"ANSI_RESET"   thread: %lx",already,n,already+n,st_size,d,LLU(d->fhandle_fh), pthread_self());
            ASSERT(already+n<=st_size);
            if ((already+=n)>d->preloadram->preloadram_already) d->preloadram->preloadram_already=already;
            PRELOADFILE_ROOT_UPDATE_TIME(d,r,true);
          }
        }
        unlock(mutex_fhandle);
    if (!more) break; /* d is marked for destruct and d->preloadram not shared with other fHandle_t */
  }/*for already*/
  bool ok_crc=true;
  const char *msg=NULL;
      lock(mutex_fhandle);
      ASSERT_D_READING(d);
      if (already!=st_size){ /* Not Completely read */
        if (more) msg=RED_WARNING" already!=st_size";
      }else if (iszip){ // USED_TO_BE_ZP_TRY_ZIP
        d->flags|=FHANDLE_PRELOADRAM_COMPLETE;
        LOCK(mutex_fhandle, ok_crc=fhandle_check_crc32(d));
        fhandle_counter_inc(d,ok_crc?ZIP_READ_CACHE_CRC32_SUCCESS:ZIP_READ_CACHE_CRC32_FAIL);
        msg=ok_crc?GREEN_SUCCESS" crc32 OK":RED_WARNING" already==st_size  crc32 wrong";
        if (ok_crc) d->preloadram->preloadram_took_mseconds=currentTimeMillis()-start;
      }
ASSERT_D_READING(d);
  unlock(mutex_fhandle);
  if (msg && (LOG_FLAG_P(LOG_PRELOADRAM)||!ok||!ok_crc))log_exited_function("%s  %s  st_size: %'lld  ok:%d ok_crc:%d\n",rp,msg,LLD(st_size),ok,ok_crc);
  if (fd) close(fd);
  my_zip_fclose(zf,rp);
  my_zip_close(za,__func__);
  //log_exited_function("ZP_IS_ZIP:%d rp: %s  e: %s ok: %d  more: %d    already:%ld st_size:%ld",iszip,rp,D_EP(d),ok,more, already,st_size);

}

/////////////////////////////////////////////////////////////////////////////////
/// Directly set bytes to struct preloadram                                     ///
/// Needed for fileconversion and for getting the real file path with suffix @SOURCE ///
/////////////////////////////////////////////////////////////////////////////////
static bool fhandle_set_text(fHandle_t *d, textbuffer_t *b){
  ASSERT_LOCKED_FHANDLE();
  struct preloadram *m=preloadram_new(d);
  if (b==m->txtbuf) return true;
  if(m->txtbuf) return false; /* This can be triggered by special files */
  m->txtbuf=b;
  m->preloadram_already=m->preloadram_l=textbuffer_length(b);
  d->flags|=FHANDLE_PRELOADRAM_COMPLETE;
  return true;
}
static textbuffer_t *fhandle_set_text_or_free(fHandle_t *d,textbuffer_t *b){
      lock(mutex_fhandle);
      if (!fhandle_set_text(d,b)){
        FREE_NULL_MALLOC_ID(b);
      }else{
        preloadram_set_status(d,PRELOADRAM_DONE);
        d->flags|=FHANDLE_PRELOADRAM_COMPLETE;
      }
  unlock(mutex_fhandle);
  return b;
}
/* If infloop_PTHREAD_PRELOAD() has not been run before, start it.
   Add to queue
   Wait for completion  or at least min_fill. */
static bool preloadram_wait(fHandle_t *d, const off_t min_fill){
  root_start_thread(D_ROOT(d),PTHREAD_PRELOAD,false);
  cg_thread_assert_not_locked(mutex_fhandle);
  assert(fhandle_active_readers_writers(d));
  ASSERT(D_ROOT(d));
  {
        lock(mutex_fhandle);
        ASSERT(d->accesstime);
        if (!d->preloadram) preloadram_infer_from_other_handle(d);

        if (!d->preloadram){
          preloadram_new(d);
          d->preloadram->txtbuf=textbuffer_new(COUNT_MALLOC_PRELOADRAM_TXTBUF);
          preloadram_set_status(d,PRELOADRAM_QUEUED);
          PRELOADFILE_ROOT_UPDATE_TIME(d,NULL,false);
        }
        unlock(mutex_fhandle);
  }
 again_with_other_root:
  for(int i=0;;i++){
    LOCK_N(mutex_fhandle,
           ASSERT(is_preloadram(d,NULL));
           const off_t a=d->preloadram->preloadram_already;
           const off_t min_f=MIN(d->preloadram->preloadram_l,min_fill);
           const enum enum_preloadram_status status=PRS(d));
    if (a>=min_f) return true;
    if (status!=PRELOADRAM_READING && status!=PRELOADRAM_QUEUED){
      if (status!=PRELOADRAM_DONE) DIE_DEBUG_NOW("(%d)   !PRELOADRAM_READING && !PRELOADRAM_QUEUED   preloadram:%p  status:%d already:%lld",i,d->preloadram, status,LLD(a));
      log_debug_now("Going return false.  status: %s already:%'lld  min_f: %'lld  size: %'lld",enum_preloadram_status_S[status],LLD(a),LLD(min_f),LLD(D_ST_SIZE(d)));
      return false;
    }
    if (preloadfile_time_exceeded(__func__,d,COUNT_PRELOADRAM_WAITFOR_TIMEOUT)) break;
    usleep(50+MIN(i,1<<18));
    if (!(i&1023)) fputc(status==PRELOADRAM_QUEUED?'q':'r',stderr);
  }
  zpath_t zp={0};
  LOCK_N(mutex_fhandle, ASSERT(is_preloadram(d,NULL)); zp=d->preloadram->m_zpath);
  if (find_realpath_other_root(&zp)){
        lock(mutex_fhandle);
        d->preloadram->m_zpath=zp;
        d->preloadram->preloadram_already=0;
        PRELOADFILE_ROOT_UPDATE_TIME(d,NULL,false);
        unlock(mutex_fhandle);
    goto again_with_other_root;
  }/* i */
  return false;
}


// COUNT_MALLOC_PRELOADRAM_TXTBUF cg_free_null_malloc_id COUNT_S textbuffer   textbuffer_new(COUNT_MALLOC_PRELOADRAM_TXTBUF)
// preloadram_l
